"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _admin_document_types from './admin-document-types.bones.json'
import _admin_users from './admin-users.bones.json'
import _citizen_applications from './citizen-applications.bones.json'
import _citizen_grievances from './citizen-grievances.bones.json'
import _citizen_dashboard from './citizen-dashboard.bones.json'
import _officer_dashboard from './officer-dashboard.bones.json'
import _officer_grievances from './officer-grievances.bones.json'

registerBones({
  "admin-document-types": _admin_document_types,
  "admin-users": _admin_users,
  "citizen-applications": _citizen_applications,
  "citizen-grievances": _citizen_grievances,
  "citizen-dashboard": _citizen_dashboard,
  "officer-dashboard": _officer_dashboard,
  "officer-grievances": _officer_grievances,
})
