"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _citizen_grievances from './citizen-grievances.bones.json'
import _citizen_dashboard from './citizen-dashboard.bones.json'
import _officer_grievances from './officer-grievances.bones.json'
import _officer_dashboard from './officer-dashboard.bones.json'

registerBones({
  "citizen-grievances": _citizen_grievances,
  "citizen-dashboard": _citizen_dashboard,
  "officer-grievances": _officer_grievances,
  "officer-dashboard": _officer_dashboard,
})
